### ISSUE TITLE
please fix this issue

### ISSUE THREAD

**Issue by onkar-cis** [mattludwigs/elm-version-manager#9]
evm use 0.17.0
Using: 0.17.0

fs.js:1054
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: ENOENT: no such file or directory, symlink '/home/cis/evm/0.17.0/elm' -> '/usr/local/bin/elm'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at /usr/lib/node_modules/elm-version-manager/index.js:111:14
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by mattludwigs** [comment]
@onkar-cis Thank you for the report, I am going to try to circle back around to fully updating this some time closer to mid summer. I have a lot on my plate currently, thank you for your patience!
